In [2]:
#Day6 15:45 ~16:00
import pandas as pd
import numpy as np
import quandl

In [3]:
sunspots = quandl.get("SIDC/SUNSPOTS_A")

In [4]:
sunspots

,Yearly Mean Total Sunspot Number,Yearly Mean Standard Deviation,Number of Observations,Definitive/Provisional Indicator
Date,,,,
1700-12-31,8.3,NaN,NaN,1.0
1701-12-31,18.3,NaN,NaN,1.0
1702-12-31,26.7,NaN,NaN,1.0
1703-12-31,38.3,NaN,NaN,1.0
1704-12-31,60.0,NaN,NaN,1.0
1705-12-31,96.7,NaN,NaN,1.0
1706-12-31,48.3,NaN,NaN,1.0
1707-12-31,33.3,NaN,NaN,1.0
1708-12-31,16.7,NaN,NaN,1.0
1709-12-31,13.3,NaN,NaN,1.0
1710-12-31,5.0,NaN,NaN,1.0
1711-12-31,0.0,NaN,NaN,1.0
1712-12-31,0.0,NaN,NaN,1.0
1713-12-31,3.3,NaN,NaN,1.0
1714-12-31,18.3,NaN,NaN,1.0
1715-12-31,45.0,NaN,NaN,1.0
1716-12-31,78.3,NaN,NaN,1.0
1717-12-31,105.0,NaN,NaN,1.0
1718-12-31,100.0,NaN,NaN,1.0
1719-12-31,65.0,NaN,NaN,1.0
1720-12-31,46.7,NaN,NaN,1.0
1721-12-31,43.3,NaN,NaN,1.0
1722-12-31,36.7,NaN,NaN,1.0
1723-12-31,18.3,NaN,NaN,1.0
1724-12-31,35.0,NaN,NaN,1.0
1725-12-31,66.7,NaN,NaN,1.0
1726-12-31,130.0,NaN,NaN,1.0
1727-12-31,203.3,NaN,NaN,1.0
1728-12-31,171.7,NaN,NaN,1.0
1729-12-31,121.7,NaN,NaN,1.0
...,...,...,...,...
1989-12-31,211.1,12.8,6932.0,1.0
1990-12-31,191.8,11.2,7108.0,1.0
1991-12-31,203.3,12.7,6932.0,1.0
1992-12-31,133.0,8.9,7845.0,1.0
1993-12-31,76.1,5.8,8010.0,1.0
1994-12-31,44.9,4.4,8524.0,1.0
1995-12-31,25.1,3.7,8429.0,1.0
1996-12-31,11.6,3.1,7614.0,1.0
1997-12-31,28.9,3.6,7294.0,1.0
1998-12-31,88.3,6.6,6353.0,1.0
1999-12-31,136.3,9.3,6413.0,1.0
2000-12-31,173.9,10.1,5953.0,1.0
2001-12-31,170.4,10.5,6558.0,1.0
2002-12-31,163.6,9.8,6588.0,1.0
2003-12-31,99.3,7.1,7087.0,1.0
2004-12-31,65.3,5.9,6882.0,1.0
2005-12-31,45.8,4.7,7084.0,1.0
2006-12-31,24.7,3.5,6370.0,1.0
2007-12-31,12.6,2.7,6841.0,1.0
2008-12-31,4.2,2.5,6644.0,1.0
2009-12-31,4.8,2.5,6465.0,1.0
2010-12-31,24.9,3.4,6328.0,1.0
2011-12-31,80.8,6.7,6077.0,1.0
2012-12-31,84.5,6.7,5753.0,1.0
2013-12-31,94.0,6.9,5347.0,1.0
2014-12-31,113.3,8.0,5273.0,1.0
2015-12-31,69.8,6.4,8903.0,1.0
2016-12-31,39.8,3.9,9940.0,1.0
2017-12-31,21.7,2.5,11444.0,1.0
2018-12-31,7.1,1.1,11739.0,0.0

In [8]:
#head 맨위 부터, tail은 맨 아래 부터
print("Head 2", sunspots.head(2))
print("####")
print("Tail 2", sunspots.tail(2))

Head 2             Yearly Mean Total Sunspot Number  Yearly Mean Standard Deviation  \
Date
1700-12-31                               8.3                             NaN
1701-12-31                              18.3                             NaN

            Number of Observations  Definitive/Provisional Indicator
Date
1700-12-31                     NaN                               1.0
1701-12-31                     NaN                               1.0
####
Tail 2             Yearly Mean Total Sunspot Number  Yearly Mean Standard Deviation  \
Date
2017-12-31                              21.7                             2.5
2018-12-31                               7.1                             1.1

            Number of Observations  Definitive/Provisional Indicator
Date
2017-12-31                 11444.0                               1.0
2018-12-31                 11739.0                               0.0

In [14]:
#마지막 날짜를 사용해 마지막 값을 검색
last_date = sunspots.index[-1]
print("Last value\n", sunspots.loc[last_date])

Last value
 Yearly Mean Total Sunspot Number        7.1
Yearly Mean Standard Deviation          1.1
Number of Observations              11739.0
Definitive/Provisional Indicator        0.0
Name: 2018-12-31 00:00:00, dtype: float64

In [15]:
#날짜형식으로 검색
print("Values slice by date:\n", sunspots["20020101": "20131231"])

Values slice by date:
             Yearly Mean Total Sunspot Number  Yearly Mean Standard Deviation  \
Date
2002-12-31                             163.6                             9.8
2003-12-31                              99.3                             7.1
2004-12-31                              65.3                             5.9
2005-12-31                              45.8                             4.7
2006-12-31                              24.7                             3.5
2007-12-31                              12.6                             2.7
2008-12-31                               4.2                             2.5
2009-12-31                               4.8                             2.5
2010-12-31                              24.9                             3.4
2011-12-31                              80.8                             6.7
2012-12-31                              84.5                             6.7
2013-12-31                              94.0                             6.9

            Number of Observations  Definitive/Provisional Indicator
Date
2002-12-31                  6588.0                               1.0
2003-12-31                  7087.0                               1.0
2004-12-31                  6882.0                               1.0
2005-12-31                  7084.0                               1.0
2006-12-31                  6370.0                               1.0
2007-12-31                  6841.0                               1.0
2008-12-31                  6644.0                               1.0
2009-12-31                  6465.0                               1.0
2010-12-31                  6328.0                               1.0
2011-12-31                  6077.0                               1.0
2012-12-31                  5753.0                               1.0
2013-12-31                  5347.0                               1.0

In [17]:
#16:45 ~ 17:25
print("Slice from a list of indices:\n", sunspots.iloc[[2,4,-4,-2]])

Slice from a list of indices:
             Yearly Mean Total Sunspot Number  Yearly Mean Standard Deviation  \
Date
1702-12-31                              26.7                             NaN
1704-12-31                              60.0                             NaN
2015-12-31                              69.8                             6.4
2017-12-31                              21.7                             2.5

            Number of Observations  Definitive/Provisional Indicator
Date
1702-12-31                     NaN                               1.0
1704-12-31                     NaN                               1.0
2015-12-31                  8903.0                               1.0
2017-12-31                 11444.0                               1.0

In [21]:
#통계표
print("Describe", sunspots.describe(),"\n")

Describe        Yearly Mean Total Sunspot Number  Yearly Mean Standard Deviation  \
count                        319.000000                      201.000000
mean                          78.970846                        7.947761
std                           62.019506                        3.840522
min                            0.000000                        1.100000
25%                           24.800000                        4.700000
50%                           65.800000                        7.600000
75%                          115.750000                       10.400000
max                          269.300000                       19.100000

       Number of Observations  Definitive/Provisional Indicator
count              201.000000                        319.000000
mean              1568.412935                          0.996865
std               2650.501617                          0.055989
min                150.000000                          0.000000
25%                365.000000                          1.000000
50%                365.000000                          1.000000
75%                366.000000                          1.000000
max              11739.000000                          1.000000

In [22]:
#카운트
print("count", sunspots.count(), "\n")

count Yearly Mean Total Sunspot Number    319
Yearly Mean Standard Deviation      201
Number of Observations              201
Definitive/Provisional Indicator    319
dtype: int64

In [24]:
#표준 편차
print(sunspots.mad(), "\n")

Yearly Mean Total Sunspot Number      50.954012
Yearly Mean Standard Deviation         3.155848
Number of Observations              1983.714512
Definitive/Provisional Indicator       0.006250
dtype: float64

In [31]:
#중앙값
print(sunspots.median(), "\n")
#최댓값
print(sunspots.max(), "\n")
#최솟값
print(sunspots.min(), "\n")
#최빈값
print(sunspots.mode(), "\n")

Yearly Mean Total Sunspot Number     65.8
Yearly Mean Standard Deviation        7.6
Number of Observations              365.0
Definitive/Provisional Indicator      1.0
dtype: float64

Yearly Mean Total Sunspot Number      269.3
Yearly Mean Standard Deviation         19.1
Number of Observations              11739.0
Definitive/Provisional Indicator        1.0
dtype: float64

Yearly Mean Total Sunspot Number      0.0
Yearly Mean Standard Deviation        1.1
Number of Observations              150.0
Definitive/Provisional Indicator      0.0
dtype: float64

   Yearly Mean Total Sunspot Number  Yearly Mean Standard Deviation  \
0                              18.3                             9.2

   Number of Observations  Definitive/Provisional Indicator
0                   365.0                               1.0

In [33]:
#분산의 제곱근
print(sunspots.std(), "\n")
#분산을 반환
print(sunspots.var(), "\n")

Yearly Mean Total Sunspot Number      62.019506
Yearly Mean Standard Deviation         3.840522
Number of Observations              2650.501617
Definitive/Provisional Indicator       0.055989
dtype: float64

Yearly Mean Total Sunspot Number    3.846419e+03
Yearly Mean Standard Deviation      1.474961e+01
Number of Observations              7.025159e+06
Definitive/Provisional Indicator    3.134796e-03
dtype: float64

In [34]:
#비대칭 반환 
print(sunspots.skew())

Yearly Mean Total Sunspot Number     0.810805
Yearly Mean Standard Deviation       0.546692
Number of Observations               1.936611
Definitive/Provisional Indicator   -17.860571
dtype: float64

In [36]:
#첨도
print(sunspots.kurt())

Yearly Mean Total Sunspot Number     -0.127590
Yearly Mean Standard Deviation       -0.252353
Number of Observations                2.460041
Definitive/Provisional Indicator    319.000000
dtype: float64