In [1]:
import pandas as pd

In [3]:
dan1 = pd.Series(range(10))
dan2 = dan1 *2
dan3 = dan1 *3
dan4 = dan1 *4
dan5 = dan1 *5
dan6 = dan1 *6
dan7 = dan1 *7
dan8 = dan1 *8
dan9 = dan1 *9

data = {
    '1단' : dan1,
    '2단' : dan2,
    '3단' : dan3,
    '4단' : dan4,
    '5단' : dan5,
    '6단' : dan6,
    '7단' : dan7,
    '8단' : dan8,
    '9단' : dan9
}

se2 = pd.DataFrame(data)
se2

   1단  2단  3단  4단  5단  6단  7단  8단  9단
0   0   0   0   0   0   0   0   0   0
1   1   2   3   4   5   6   7   8   9
2   2   4   6   8  10  12  14  16  18
3   3   6   9  12  15  18  21  24  27
4   4   8  12  16  20  24  28  32  36
5   5  10  15  20  25  30  35  40  45
6   6  12  18  24  30  36  42  48  54
7   7  14  21  28  35  42  49  56  63
8   8  16  24  32  40  48  56  64  72
9   9  18  27  36  45  54  63  72  81

In [4]:
#df.sort_index(by=['',''], asending=[True, False])
se2.T

    0  1   2   3   4   5   6   7   8   9
1단  0  1   2   3   4   5   6   7   8   9
2단  0  2   4   6   8  10  12  14  16  18
3단  0  3   6   9  12  15  18  21  24  27
4단  0  4   8  12  16  20  24  28  32  36
5단  0  5  10  15  20  25  30  35  40  45
6단  0  6  12  18  24  30  36  42  48  54
7단  0  7  14  21  28  35  42  49  56  63
8단  0  8  16  24  32  40  48  56  64  72
9단  0  9  18  27  36  45  54  63  72  81

In [6]:
df2 = se2['7'] + se2['9']

KeyError: '7'